config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(message_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div>
<%= message %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      
<%= render 'layouts/flash_messages' %>


      
<%= yield %>

    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 のメッセージ編集ページ</h1>

<%= form_for(@task) do |f| %>

  
<%= f.label :content, 'メッセージ' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', messages_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  
  <%= @tasks.each do |task| %>
    
    <li>
      <%= link_to task.id, task %> : <%= task.content %>
    </li>
  
  <% end %>
  
</ul>

<%= link_to '新規タスクの投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規投稿ページ</h1>

<%= form_for(@task) do |f| %>

  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: 
<%= @task.id %>
 のメッセージ詳細ページ</h1>

<p>
<%= @task.content %>
</p>

<%= link_to '一覧に戻る', tasks_path %>

<%= link_to 'このメッセージを編集する', edit_task_path(@task) %>
 
<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>